name = "domains"
compatibility_date = "2024-02-04"

[build]
command = "npm run build"

[site]
bucket = "./out"

# 添加 pages_build_output_dir
pages_build_output_dir = "out"

# 添加 main 字段
main = "./functions/_worker.js"

[functions]
directory = "./functions"

[[kv_namespaces]]
binding = "MESSAGES"
id = "031053abc53c4fe1a672bdb3a242e451" 