name = "domains"
compatibility_date = "2024-02-04"
nodejs_compat = true

[build]
command = "npm run build"

[site]
bucket = "./out"

# Pages 配置
[pages]
build_output_dir = "out"
functions_dir = "functions"

# KV 绑定
[[kv_namespaces]]
binding = "MESSAGES"
id = "031053abc53c4fe1a672bdb3a242e451"

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "031053abc53c4fe1a672bdb3a242e451"  # 使用相同的 KV 命名空间

# 环境变量
[vars]
VAPID_PUBLIC_KEY = "BIxxVmoXcHlWCbjsx70Ko79302Zq6giIE6G5JnjhAVLuOwaKMDqdA7B66cno222VhlhZeOqmUlZJkziZxe387d4"
VAPID_PRIVATE_KEY = "UeDRSoLasTWDdeCJ1MM-La5gyxBH7f2_Af-3mXREoGw" 