name = "domains"
compatibility_date = "2024-02-04"

[build]
command = "npm run build"

[site]
bucket = "./out"

# Pages 配置
[pages]
build_output_dir = "out"
functions_dir = "functions"

# KV 绑定
[[kv_namespaces]]
binding = "MESSAGES"
id = "031053abc53c4fe1a672bdb3a242e451" 