name = "domains"
compatibility_date = "2024-02-04"

[build]
command = "npm run build"

[site]
bucket = "./out"

[functions]
directory = "./functions"

[[kv_namespaces]]
binding = "MESSAGES"
id = "YOUR_KV_ID"
preview_id = "YOUR_PREVIEW_KV_ID" 