name = "domains"
compatibility_date = "2024-02-04"

[build]
command = "npm run build"

[site]
bucket = "./out"

[functions]
directory = "./functions"

[[kv_namespaces]]
binding = "MESSAGES"
id = "031053abc53c4fe1a672bdb3a242e451" 